const express = require("express");
const router = express.Router();
const addnodes = require("../models/sankeynodes");
const { translate } = require('free-translate');
const multer = require("multer");

const storage = multer.diskStorage({
  destination: function (req, file, next) {
    next(null, "public/nodes");
  },
  filename: function (req, file, next) {
    let { id } = req.body;
    // Use the filename generated by Multer
    const filename = id + ".png";
    next(null, filename);
  },
  
});
const profile = multer({ storage });

const defaultImageUrl = "public/nodes/Default+Image.svg"

router.post("/", profile.single("image"), async (req, res) => {
  try {
    const { role } = req.authData;
    if (req.authData) {
      if (role !== "admin") {
        throw {
          status: 403,
          message: "Access forbidden. You are not an admin.",
        };
      }
    }

    const { id, colour } = req.body;

    if (!id) return res.status(400).send("Required field cannot be empty");

    const node = await addnodes.findOne({ where: { id: id } });
    if (node) return res.status(400).send("This node already exists.");

    const img = `${id}.png`;

    // Create the node record with id and color
    let addnode = await addnodes.create({
      id: id,
      colour: colour,
      image: img,
    });

    // Send the response with the node information
    res.status(200).send({ message: "Node added successfully", addnode });

    // Translate to French and update the database
    translate(id, { from: 'en', to: 'fr' })
      .then(async (translatedText) => {
        await addnodes.update({ id_french: translatedText }, {
          where: { id: id }
        });
        console.log("French stored");
      });

    // Translate to Portuguese and update the database
    translate(id, { from: 'en', to: 'pt' })
      .then(async (translatedText) => {
        await addnodes.update({ id_portegues: translatedText }, {
          where: { id: id }
        });
        console.log("Portuguese stored");
      });
  } catch (err) {
    console.log(err);
    res.status(400).send("Something went wrong!");
  }
});

module.exports = router;
